### ISSUE TITLE
Tease apart the "available_on" into a joining data structure

### ISSUE THREAD

**Issue by jeremyf** [samvera-labs/houndstooth#26]
This is related to #21 

When I'm thinking about iterating over the m3 data to build a dynamic form, I'd be expecting to iterate on something like:

```json
{
  "class": "genericWork",
  "properties": [
    {
      "property": "creator",
      "overrides": {
        "display_label": "My Custom Creator",
        "controlled_vocabulary_uri": "https://only.creatives.net/creators"
      }
    }
  ]
}
```

When I encounter a "property", I would retrieve the property's m3 data, and merge that with the overrides. I would favor overrides.

## Join Table between Class and Property

I also believe, from a structural standpoint, you may want to consider a "joining" data structure for class and property. (I'm thinking in terms of databases and how I would structure these in SQL) The "available_on" attribute of a "property" feels very funny. The "joining" data structure would also provide guidance on sequence of rendering. And would make it trivial to add the controlled vocabularies.

```yaml
class_properties:
  class: genericWork
  properties:
  - property: title
  - property: creator
```

## Building Further

It may make sense to further break out controlled vocabularies as their own "table", then you could repurpose those controlled vocabularies across different classes/properties.

**Comment by jeremyf** [comment]
I wrote up a bit of a how to render something vaguely resembling `h3.yml` via Hugo. I believe the post alludes to how we might render complex object/properties methods.

https://takeonrules.com/2020/05/01/hugo-tips-and-tricks-1/

**Comment by no-reply** [comment]
i'm not sure i understand the motivation for `overrides`.

re: `class_properties` it seems like an approach like this is compatible with the `available_on` approach. indeed, it seems like the whole property specification could (optionally) be nested.

:-1: on `class_properties:` as a key, though. we already have `classes:` and it seems natural to add a `properties` key in that context:

```yaml
classes:
  genericWork:
    display_label: "Generic Work"
    properties:
      creator:
        display_label:
          default: "Creator(s)"
        definition:
          default: "A person or organization responsible for creating the resource."
        usage_guidelines:
          default: "Record in lastname, firstname order."
        requirement: "recommended, if applicable"
        property_uri: http://purl.org/dc/elements/1.1/creator
    title:
  collection:
    display_label: "Collection"
    properties:
      title:
  agent:
    display_label: "Agent"
    schema_uri: http://id.loc.gov/ontologies/bibframe/Agent

properties:
  title:
    display_label:
      default: "Title"
    definition:
      default: "A name to aid in identifying a work or collection."
      collection: "A name to aid in identifying the Administrative Set and to distinguish it from other Administrative Sets in the repository."
    requirement: required
    sample_value: 
      - "On the Road"
    property_uri: http://purl.org/dc/terms/title
```
